server:
  port: 8073

spring:
  application:
    name: zephyr-system

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/zephyr_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: zephyr
    password: "Zr#db#0830"

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ""
      database: 0
      timeout: 2000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8849
        username: nacos
        password: nacos
      config:
        server-addr: localhost:8849
        username: nacos
        password: nacos

  config:
    import:
      - optional:nacos:application.yaml?refreshEnabled=true

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.alibaba.nacos: OFF
    com.alibaba.nacos.client: OFF
    com.baomidou.mybatisplus: DEBUG
    org.mybatis: DEBUG

mybatis-plus:
  configuration:
    # 使用 SLF4J 打印日志（配合 logback）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true   # 下划线转驼峰，可选

# 文档配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
knife4j:
  enable: true
  setting:
    language: zh_cn