server:
  port: 9001

spring:
  application:
    name: zephyr-generator
  cloud:
    nacos:
      discovery:
        server-addr: ${SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR:localhost:8849}
      config:
        server-addr: ${SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR:localhost:8849}
        file-extension: yml
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/zephyr_db?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true}
    username: ${SPRING_DATASOURCE_USERNAME:zephyr}
    password: ${SPRING_DATASOURCE_PASSWORD:Zr#db#0830}
    driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.zephyr.generator.pojo.entity
  global-config:
    db-config:
      id-type: auto

# Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

knife4j:
  enable: true
