server:
  port: 8072

zephyr:
  gateway:
    secret: zephyr-gateway-secret-key-2026

spring:
  application:
    name: zephyr-common
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://81.70.160.181:3307/zephyr_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: zephyr
    password: "Zr#db#0830"
  data:
    redis:
      host: 81.70.160.181
      port: 6380
      password: ""
      database: 0
      timeout: 2000
  cloud:
    nacos:
      discovery:
        server-addr: 81.70.160.181:8849
        username: nacos
        password: nacos
      config:
        server-addr: 81.70.160.181:8849
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:application.yaml?refreshEnabled=true

jwt:
  algorithm: ES256
  expiration: 3600000
  es256:
    privateKey: MEECAQAwEwYHKoZIzj0CAQYIKoZIzj0DAQcEJzAlAgEBBCAeWfO36CnZzvm3R8XlA2tv7d6Jw/vbsCx5PfGg1CMRoQ==
    publicKey: MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEq8rKNtWMFhgkNos/70ciF7kzAUY4B+Qgo2GhRm/lhmJ8U9mO5TnRGeFm1qS29HraAqDBAS+JIQJV89KjH8l4xw==

management:
  endpoints:
    web:
      exposure:
        include: mappings,beans,env

logging:
  level:
    com.alibaba.nacos: OFF
    com.alibaba.nacos.client: OFF
    com.baomidou.mybatisplus: DEBUG
    org.mybatis: DEBUG

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs

knife4j:
  enable: true
  setting:
    language: zh_cn