spring:
  application:
    name: zephyr-rule

  cloud:
    nacos:
      discovery:
        server-addr: 115.190.86.189:11003
      config:
        server-addr: 115.190.86.189:11003
        file-extension: yml,yaml
        namespace: public
        group: DEFAULT_GROUP

  config:
    import:
      - optional:nacos:application.yaml?group=DEFAULT_GROUP&refreshEnabled=true
server:
  port: 9301
