import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

public class TestDB6 {
    public static void main(String[] args) throws Exception {
        Class.forName("com.mysql.cj.jdbc.Driver");
        String url = "jdbc:mysql://81.70.160.181:3307/zephyr_admin_sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai";
        String user = "root";
        String pass = "8D72A8084a44";
        try (Connection conn = DriverManager.getConnection(url, user, pass)) {
            String newHash = "$2b$10$jyO/AQ2Ylex.2l6yLTJdaeE9pLIumAc/bDkos.10kFs039ZgeYoVK"; // generated by bcryptjs
            String sql = "UPDATE zephyr_sys_user SET password = ? WHERE code = 'admin'";
            try (PreparedStatement ps = conn.prepareStatement(sql)) {
                ps.setString(1, newHash);
                int count = ps.executeUpdate();
                System.out.println("Updated " + count + " rows with new BCrypt hash.");
            }
        }
    }
}
